import { Resend } from "resend";
import { z } from "zod";
import { env } from "@/config/env";

const resend = new Resend(env.RESEND_API_KEY);

const PROVIDER_NAME = "resend";
const SUBJECT = "Your CUATClub invitation code";
const REGISTER_PATH = "/register";
const INVITE_CODE_PARAM = "inviteCode";

export class MailValidationError extends Error {
  readonly field: "to" | "inviteCode";

  constructor(field: "to" | "inviteCode", message: string) {
    super(message);
    this.name = "MailValidationError";
    this.field = field;
  }
}

export class MailDeliveryError extends Error {
  readonly retryable: boolean;
  readonly providerName: string;

  constructor(message: string, retryable: boolean, providerName: string) {
    super(message);
    this.name = "MailDeliveryError";
    this.retryable = retryable;
    this.providerName = providerName;
  }
}

export interface SendClubInviteCodeEmailParams {
  /** Club email; single recipient by design, never an array. */
  to: string;
  /** Generated by #69, not here. */
  inviteCode: string;
  /** Optional, used in the greeting. */
  clubName?: string;
}

export interface SendClubInviteCodeEmailResult {
  messageId: string;
}

/**
 * Zod .email() is a shape check, not a single-address check. Do not assume it rejects
 * "a@x.com,b@y.com" or embedded CRLF. These refinements make the single-recipient
 * anti-fan-out invariant an explicit, tested property of this file.
 */
const recipientSchema = z
  .string()
  .min(1)
  .max(254)
  .email()
  .refine((v) => !/[,;]/.test(v), { message: "must be a single email address" })
  .refine((v) => !/[\r\n\t]/.test(v), { message: "must not contain control characters" })
  .refine((v) => (v.match(/@/g) ?? []).length === 1, { message: "must contain exactly one @" })
  .refine((v) => v === v.trim(), { message: "must not have surrounding whitespace" });

const inviteCodeSchema = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[A-Za-z0-9_-]+$/, { message: "invalid invite code format" });

const clubNameSchema = z
  .string()
  .min(1)
  .max(120)
  .refine((v) => !/[\r\n]/.test(v), { message: "must not contain line breaks" })
  .optional();

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function maskEmail(email: string): string {
  const atIndex = email.indexOf("@");
  if (atIndex <= 0) return "***";
  const domain = email.slice(atIndex);
  return `${email[0]}***${domain}`;
}

function buildRegisterUrl(inviteCode: string): string {
  const url = new URL(REGISTER_PATH, env.APP_BASE_URL);
  url.searchParams.set(INVITE_CODE_PARAM, inviteCode);
  return url.toString();
}

function renderHtml(inviteCodeHtml: string, greetingNameHtml: string, registerUrlHtml: string) {
  return `<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Your CUATClub invitation code</title>
</head>
<body style="margin:0; padding:0; background-color:#f0f0f0; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%;">

  <!-- Preheader (hidden, shows in inbox preview) -->
  <div style="display:none; max-height:0; max-width:0; overflow:hidden; opacity:0; mso-hide:all; font-size:1px; line-height:1px; color:#f0f0f0;">
    Your CUATClub invitation code is inside. It can only be used once, so keep it safe.
  </div>
  <!-- Spacer to push preheader text away from visible content in some clients -->
  <div style="display:none; max-height:0; overflow:hidden; mso-hide:all;">
    &nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;
  </div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color:#f0f0f0;">
    <tr>
      <td align="center" style="padding:24px 16px;">

        <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px; max-width:600px; background-color:#ffffff; border:1px solid #ececec;">

          <!-- Header band -->
          <tr>
            <td align="center" style="background-color:#dd598c; padding:28px 24px;">
              <span style="font-family:Arial, Helvetica, sans-serif; font-size:22px; line-height:28px; font-weight:700; color:#ffffff; letter-spacing:0.5px;">CUATClub</span>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:36px 40px 8px 40px; font-family:Arial, Helvetica, sans-serif;">
              <p style="margin:0 0 4px 0; font-size:14px; line-height:20px; color:#595959;">Hi ${greetingNameHtml},</p>
              <h1 style="margin:0; font-size:20px; line-height:28px; font-weight:700; color:#0a0a0a;">Here is your invitation code</h1>
            </td>
          </tr>

          <!-- Code block -->
          <tr>
            <td align="center" style="padding:24px 40px 8px 40px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td align="center" style="background-color:#f8dee8; border:2px solid #dd598c; padding:18px 32px;">
                    <span style="font-family:'Courier New', Courier, monospace; font-size:32px; line-height:38px; font-weight:700; letter-spacing:6px; color:#0a0a0a;">${inviteCodeHtml}</span>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Instructions -->
          <tr>
            <td align="center" style="padding:16px 40px 0 40px; font-family:Arial, Helvetica, sans-serif;">
              <p style="margin:0; font-size:14px; line-height:21px; color:#595959;">
                This code can only be used once. Enter it on the registration page to complete your club's sign-up.
              </p>
            </td>
          </tr>

          <!-- CTA button -->
          <tr>
            <td align="center" style="padding:28px 40px 8px 40px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td align="center" style="background-color:#dd598c;">
                    <a href="${registerUrlHtml}" target="_blank" style="display:inline-block; padding:12px 32px; font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:20px; font-weight:700; color:#ffffff; text-decoration:none;">Register your club</a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Fallback URL -->
          <tr>
            <td align="center" style="padding:8px 40px 32px 40px; font-family:Arial, Helvetica, sans-serif;">
              <p style="margin:0; font-size:12px; line-height:18px; color:#707070; word-break:break-all;">
                Or copy this link into your browser:<br>
                <a href="${registerUrlHtml}" target="_blank" style="color:#dd598c; text-decoration:underline;">${registerUrlHtml}</a>
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:20px 40px; border-top:1px solid #ececec; font-family:Arial, Helvetica, sans-serif;" align="center">
              <p style="margin:0; font-size:12px; line-height:18px; color:#707070;">
                Didn't expect this email? You can safely ignore it — the code will not work for anyone else.
              </p>
              <p style="margin:8px 0 0 0; font-size:12px; line-height:18px; color:#acacac;">
                &copy; CUATClub
              </p>
            </td>
          </tr>

        </table>

      </td>
    </tr>
  </table>

</body>
</html>`;
}

function renderText(inviteCode: string, greetingName: string, registerUrl: string): string {
  return `Hi ${greetingName},

Here is your invitation code: ${inviteCode}

This code can only be used once. Enter it on the registration page to complete your club's sign-up.

Register your club: ${registerUrl}

Didn't expect this email? You can safely ignore it — the code will not work for anyone else.

CUATClub`;
}

/**
 * Send a club's single-use invitation code by email.
 *
 * Authorization obligations for the caller (#69):
 * - The endpoint that triggers this send MUST be an `adminProcedure`.
 * - The usecase MUST resolve `to` from a persisted club record rather than accepting a
 *   caller-supplied recipient string.
 */
export async function sendClubInviteCodeEmail(
  params: SendClubInviteCodeEmailParams
): Promise<SendClubInviteCodeEmailResult> {
  const toResult = recipientSchema.safeParse(params.to);
  if (!toResult.success) {
    throw new MailValidationError("to", "Invalid recipient email address.");
  }

  const inviteCodeResult = inviteCodeSchema.safeParse(params.inviteCode);
  if (!inviteCodeResult.success) {
    throw new MailValidationError("inviteCode", "Invalid invite code.");
  }

  const clubNameResult = clubNameSchema.safeParse(params.clubName);
  if (!clubNameResult.success) {
    throw new MailValidationError("to", "Invalid club name.");
  }

  const to = toResult.data;
  const inviteCode = inviteCodeResult.data;
  const clubName = clubNameResult.data;

  const registerUrl = buildRegisterUrl(inviteCode);
  const registerUrlHtml = escapeHtml(registerUrl);

  const greetingName = clubName ?? "there";

  const html = renderHtml(escapeHtml(inviteCode), escapeHtml(greetingName), registerUrlHtml);
  // The plain-text part is deliberately NOT escaped — HTML entities in a text/plain body are
  // a rendering bug, not a security control.
  const text = renderText(inviteCode, greetingName, registerUrl);

  try {
    const res = await resend.emails.send({
      from: `CUATClub <${env.EMAIL_FROM}>`,
      to,
      subject: SUBJECT,
      html,
      text,
    });

    if (res.error) {
      const statusCode = res.error.statusCode ?? undefined;
      const retryable = statusCode === 429 || (statusCode !== undefined && statusCode >= 500);
      console.error("mailer: resend delivery failed", {
        name: res.error.name,
        statusCode: res.error.statusCode,
        message: res.error.message,
        recipient: maskEmail(to),
      });
      throw new MailDeliveryError(
        "Unable to send email right now. Please try again later.",
        retryable,
        PROVIDER_NAME
      );
    }

    if (!res.data?.id) {
      console.error("mailer: resend returned no message id", {
        recipient: maskEmail(to),
      });
      throw new MailDeliveryError(
        "Unable to send email right now. Please try again later.",
        false,
        PROVIDER_NAME
      );
    }

    return { messageId: res.data.id };
  } catch (err) {
    if (err instanceof MailDeliveryError) throw err;

    const name = err instanceof Error ? err.name : undefined;
    const message = err instanceof Error ? err.message : undefined;
    console.error("mailer: resend send threw", {
      name,
      message,
      recipient: maskEmail(to),
    });
    throw new MailDeliveryError(
      "Unable to send email right now. Please try again later.",
      true,
      PROVIDER_NAME
    );
  }
}
